### ISSUE TITLE
Consume the Celery task queue

### ISSUE THREAD

**Issue by mugli** [IBM/node-celery-ts#33]
Is it possible to consume the queue with this client? If not yet, is that feature planned?

**Comment by Gregory-Meyer** [comment]
This client does not support consumption of tasks and it is not currently planned to add this functionality. The [ResultBackend interface](https://ibm.github.io/node-celery-ts/interfaces/resultbackend.html) supports publishing results onto a backend, but the [MessageBroker interface](https://ibm.github.io/node-celery-ts/interfaces/messagebroker.html) does not support receiving messages from a queue. If you need full first class support for consumption of Task messages, I would recommend either using the Python client or perhaps [the Go client](https://github.com/gocelery/gocelery).

**Comment by ndrsn** [comment]
Would you accept a PR implementing this functionality? (subject, of course, to prior discussion of a possible solution)
