### ISSUE TITLE
Celery Beat for node

### ISSUE THREAD

**Issue by shubhamagarwal003** [IBM/node-celery-ts#45]
This library seems very useful. But are there any support for celerybeat to schedule periodic tasks. In python there is celerybeat which could be used to schedule periodic tasks. If not what is the preferred way to do this in node ensuring that multiple app instances doesn't schedule duplicate tasks.

**Comment by Gregory-Meyer** [comment]
celery-ts doesn't currently support Celery Beat and we're not currently planning on implementing that functionality. If you want to schedule periodic tasks in an unsynchronized way, I suggest using [the Node primitives](https://nodejs.org/api/timers.html#timers_setinterval_callback_delay_args) for periodic tasks. If you want to schedule tasks in a synchronized manner, you could use Redis to synchronize across computation nodes using [Redlock](https://redis.io/topics/distlock), for example.

**Comment by dobesv** [comment]
See also https://stackoverflow.com/questions/42831624/how-to-use-celery-beat-with-node-celery
