### ISSUE TITLE
Incompatible node version

### ISSUE THREAD

**Issue by stasyaner** [IBM/node-celery-ts#46]
Hello Team. I can't install the package due to the below issue. I know that an obvious solution would be to downgrade node to somewhat closer version to 8 but I wouldn't want to downgrade node just for one package. Thank you.
`error celery-ts@1.1.0: The engine "node" is incompatible with this module. Expected version "^8.11.3". Got "11.4.0"`

**Comment by muRn** [comment]
Having the same issue with node 11.0.0:

```
error celery-ts@1.1.0: The engine "node" is incompatible with this module. Expected version "^8.11.3". Got "11.0.0"
```

**Comment by AaronBuxbaum** [comment]
Can you publish a new version to npm with this change?
