### ISSUE TITLE
Mention the client in Celery's documentation

### ISSUE THREAD

**Issue by thedrow** [IBM/node-celery-ts#48]
Hi, Celery core contributor here.

I was not aware that this client exists.
I suggest that you will issue a PR to mention it in the documentation.

**Comment by cwill747** [comment]
@thedrow is there a specific place in the Celery documentation that you would recommend? I can't seem to find a place that it would fit in.

**Comment by thedrow** [comment]
[Here](https://docs.celeryproject.org/en/latest/getting-started/introduction.html?highlight=php#what-s-a-task-queue).

**Comment by cwill747** [comment]
Pull request opened! Since we don't have control over whether or not it's merged, closing this issue as we've done what we can.
